### PR TITLE
release 1.6.2

### PR DESCRIPTION
**Pull request by ReimarBauer**

### CODE REVIEW

**Comment by jakirkham** [comment]
The error should be fixed by doing a [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` 2.4.2. Also please make sure that `conda-build-all` has been updated, `conda-build` is 2.1.x, and `conda` is 4.3.x.

**Comment by ReimarBauer** [comment]
A first trial shows another problem. How to fix this?

```
conda smithy rerender
Traceback (most recent call last):
  File "/home/user/miniconda2/bin/conda-smithy", line 6, in <module>
    exit(main())
  File "/home/user/miniconda2/lib/python2.7/site-packages/conda_smithy/cli.py", line 290, in main
    args.subcommand_func(args)
  File "/home/user/miniconda2/lib/python2.7/site-packages/conda_smithy/cli.py", line 194, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/home/user/miniconda2/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 722, in main
    render_circle(env, config, forge_dir)
  File "/home/user/miniconda2/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 72, in render_circle
    with fudge_subdir('linux-64', build_config=meta_config(meta)):
  File "/home/user/miniconda2/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/user/miniconda2/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 221, in fudge_subdir
    build_config.subdir = subdir
AttributeError: can't set attribute
```

**Comment by ReimarBauer** [comment]
```
conda                     4.3.25                   py27_0  
conda-build               3.0.19           py27h652c75d_0  
conda-build-all           1.1.1                      py_2    conda-forge
conda-env                 2.6.0                         0  
conda-smithy              2.4.2                      py_0    conda-forge

```

**Comment by ReimarBauer** [comment]
rerendered by
```
conda                     4.3.23                   py27_0    conda-forge
conda-build               2.1.17                   py27_0    conda-forge
conda-build-all           1.1.1                      py_2    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-smithy              2.4.2                      py_0    conda-forge

```

**Comment by jakirkham** [comment]
Right the error was not having `conda-build` 2.1.x (3.x is not supported yet).

**Comment by ReimarBauer** [comment]
@jakirkham I think appveyor finished, but it looks like it does not update its status.

**Comment by jakirkham** [comment]
Yep, it passed. That happens sometimes as AppVeyor runs into GitHub rate limiting. Not much we can do about it unfortunately.

**Pull request merged**
