### PR TITLE
X11 stack added

### PR DESCRIPTION
**Pull request by ReimarBauer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ReimarBauer** [comment]
@conda-forge-admin please help


The conda-verify seems to have a problem with my recipe. After I do understand that issue I likly have a 3.7 version too.

This fails for all 3.7 builds. 
I have no idea why at all it even tries 3.7 as I skipped it. 

It looks like during verification it looks up numpy without success.

```
mss-feedstock/recipe$ conda-verify .Verifying ./meta.yaml...
{'platform': 'linux', 'arch': '64', 'python': '27', 'numpy': '1.11'}
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
Adding in variants from internal_defaults
Adding in variants from config.variant
{'platform': 'linux', 'arch': '32', 'python': '27', 'numpy': '1.11'}
{'platform': 'osx', 'arch': '64', 'python': '27', 'numpy': '1.11'}
{'platform': 'win', 'arch': '32', 'python': '27', 'numpy': '1.11'}
{'platform': 'win', 'arch': '64', 'python': '27', 'numpy': '1.11'}
{'platform': 'linux', 'arch': '64', 'python': '34', 'numpy': '1.11'}
{'platform': 'linux', 'arch': '32', 'python': '34', 'numpy': '1.11'}
{'platform': 'osx', 'arch': '64', 'python': '34', 'numpy': '1.11'}
{'platform': 'win', 'arch': '32', 'python': '34', 'numpy': '1.11'}
{'platform': 'win', 'arch': '64', 'python': '34', 'numpy': '1.11'}
{'platform': 'linux', 'arch': '64', 'python': '35', 'numpy': '1.11'}
[]
Traceback (most recent call last):
  File "/home/user/miniconda3/bin/conda-verify", line 11, in <module>
    sys.exit(cli())
  File "/home/user/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda_verify/cli.py", line 32, in cli
    meta = render_metadata(path, cfg)
  File "/home/user/miniconda3/lib/python3.7/site-packages/conda_verify/utilities.py", line 105, in render_metadata
    return m.get_rendered_recipe_text()
AttributeError: 'list' object has no attribute 'get_rendered_recipe_text'
```

**Comment by mariusvniekerk** [comment]
Odds are that your py37 issues stem from missing dependencies.  A potential one is you have a pin on `matplotlib<3` which might not exist....

**Comment by ReimarBauer** [comment]
> Odds are that your py37 issues stem from missing dependencies. A potential one is you have a pin on `matplotlib<3` which might not exist....

Just found the problem. I skipped 3.5 and that is not existing anymore

**Comment by ReimarBauer** [comment]
documented the behaviour:
https://github.com/conda/conda-verify/issues/59

**Pull request merged**
