### PR TITLE
try a 3.9 build

### PR DESCRIPTION
**Pull request by ReimarBauer**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ReimarBauer** [comment]
@conda-forge-admin How can I enable a build on python 3.9 ?

**Comment by mbargull** [comment]
gh-82 was closed which is interpreted as it being "done" for the migration (hence no new Py3.9 migration PRs were opened).
Since `python=3.9` is not yet part of the general pinning, you have to manually copy https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/python39.yaml to `.ci_support/migrations/python39.yaml` in this feedstock (and rerender afterwards).

**Comment by beckermr** [comment]
That was @ocefpaf who closed it. We probably should provide hooks to revive PRs like this. cc @conda-forge/bot

**Comment by ReimarBauer** [comment]
Did some experiments yesterday, builded a new package and tried to upgrade to python 3.9 after its installation.
The dependency solver showed that there are conflicts. There are some dependencies not yet available in 3.9.
I got some different ideas from that output. 
It analyzes everything what my project is using. I never had such a deep package list before. A linked output to feedstocks would be great. I think I want that always on a build. An additional step could be to show that a dependency has a newer version but it is not used by my package. Also it may be possible to destinguish that there is a newer version on the origin than on conda-forge. It could show how old a package is.  
A condensed version could be to list only the missing packages for a given python version based on the deep list.

**Comment by wolfv** [comment]
yeah, the conda solver error output is usually unusable ... might be easier to go through the dependencies one-by-one or try to use mamba (usually easier to read errors).

**Pull request merged**
