### PR TITLE
test env var without the patches

### PR DESCRIPTION
**Pull request by ocefpaf**
The patching in #52 is masking a problem with the activation of the environmental variable during the tests. Let's test here to see if we can find out what is going on.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@ReimarBauer the problem is with `conda-build 3.18.1`, as you can see all the CIs that I downgraded to `conda-build=3.17.8` things work as expected. I already informed @msarahan and I'm opening an issue upstream to track it.

**Comment by mingwandroid** [comment]
I've fixed this already

**Comment by ocefpaf** [comment]
> I've fixed this already

Cool. We need a new release then :smile:

**Comment by mingwandroid** [comment]
urgh, sorry, PR is: https://github.com/conda/conda-build/pull/3515

**Comment by ReimarBauer** [comment]
great !

**Pull request closed without merging**
