### PR TITLE
fixed version of skyfield >=1.10

### PR DESCRIPTION
**Pull request by ReimarBauer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ReimarBauer** [comment]
@conda-forge-admin some of the failures on  CircleCI happen likly of encrypted filesystems

```
IOError: [Errno 2] No such file or directory: 
'/home/conda/feedstock_root/build_artifacts/mss_1552225791201/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share/proj/epsg'
```
appveyor fails again with

```
(%PREFIX%) %SRC_DIR%>mswms -h 
WARNING:root:Couldn't import mss_wms_settings (ImportError:'No module named 'mss_wms_settings''), creating dummy config.
WARNING:root:Couldn't import mss_wms_auth (ImportError:'{No module named 'mss_wms_auth'), creating dummy config.
Traceback (most recent call last):
  File "C:\bld\mss_1552225882672\_test_env\Scripts\mswms-script.py", line 6, in <module>
    from mslib.mswms.mswms import main
  File "C:\bld\mss_1552225882672\_test_env\lib\site-packages\mslib\mswms\mswms.py", line 78, in <module>
    from mslib.mswms.wms import mss_wms_settings, mss_wms_auth
  File "C:\bld\mss_1552225882672\_test_env\lib\site-packages\mslib\mswms\wms.py", line 99, in <module>
    from mslib.mswms import mss_plot_driver
  File "C:\bld\mss_1552225882672\_test_env\lib\site-packages\mslib\mswms\mss_plot_driver.py", line 41, in <module>
    from mslib import utils
  File "C:\bld\mss_1552225882672\_test_env\lib\site-packages\mslib\utils.py", line 47, in <module>
    import mpl_toolkits.basemap.pyproj as pyproj
  File "C:\bld\mss_1552225882672\_test_env\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\bld\\mss_1552225882672\\_test_env\\Library\\share\\proj\\epsg'
```
And why some builds on azure crashs I have no idea

Can you help?

**Comment by ReimarBauer** [comment]
@mariusvniekerk I need help. An example, some help what I should change.

**Comment by mariusvniekerk** [comment]
This error suggests there is an issue with pyproj / proj4?

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/mss_1552561837056/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share/proj/epsg'
```

**Comment by mariusvniekerk** [comment]
@ocefpaf knows this part of the stack better than I do

**Comment by ocefpaf** [comment]
@ReimarBauer you should not need all those patches when using a modern conda. All the env variables are properly initialized for you.

I sent #45 with some extras fixes.

PS: I would test `mss` with `proj4 6` in another PR.

**Pull request merged**
