### PR TITLE
version 1.4.0

### PR DESCRIPTION
**Pull request by ReimarBauer**

### CODE REVIEW

**Comment by ReimarBauer** [comment]
@ocefpaf have you an idea what else I could try for travis-ci ?

**Comment by ocefpaf** [comment]
The problem is that we don't have `qt` for `OS X` and pulling it from `defaults` brings all sort of headaches. And the reason it is pulling from `defaults` is because `pyqt` is unpinned. Try to pin it to `4.11.*` and hopefully that version is OK with our `icu` and `libxml2`.

@ccordoba12 here is the problem of unpinned `pyqt`, it may be OK for spyder dependencies but the more you mix with other software the more you'll reach incompatibilities like this.

**Comment by ccordoba12** [comment]
The problem I see here is the lack of macOS Qt 5 packages in conda-forge. I mean, you're providing your own Python, which is linked against your own `lxml`, and this one against your own `icu`. So when Qt from defaults comes in, it breaks everything because it brings its own `icu`.

So if you want a full replacement for *everything* Continuum provides, you must provide all our packages. And that has nothing to do with pinning Qt or PyQt, in my humble opinion.

**Comment by ocefpaf** [comment]
> The problem I see here is the lack of macOS Qt 5 packages in conda-forge. I mean, you're providing your own Python, which is linked against your own `lxml`, and this one against your own `icu`. So when Qt from defaults comes in, it breaks everything because it brings its own `icu`.
So if you want a full replacement for *everything* Continuum provides, you must provide all our packages. And that has nothing to do with pinning Qt or PyQt, in my humble opinion.

That is exactly why we need to pin!

**Comment by ccordoba12** [comment]
I disagree. You need to put all your efforts in compiling Qt5 in macOS.

**Comment by ccordoba12** [comment]
I mean, as I said, you wanted to be a full replacement for Anaconda, now you need to go for it.

**Comment by ocefpaf** [comment]
> I disagree. You need to put all your efforts in compiling Qt5 in macOS.

You probably understand enough about `conda-forge` to know that is not possible with the CIs, and it is not easy to get volunteers to do it on their own hardware.

> I mean, as I said, you wanted to be a full replacement for Anaconda, now you need to fully go for it.

That sounds like you want `conda-forge` to fail when a solution, that we use constantly, already exists: the pinning.

If you don't understand the limitations we have then please don't undermined the workarounds we need to make our effort work for users.

**Comment by ccordoba12** [comment]
> You probably understand enough about conda-forge to know that is not possible with the CIs, and it is not easy to get volunteers to do it on their own hardware.

Of course I know that, but we (at Continuum) also faced similar problems (Ray, Mike and me spent countless hours debugging and re-compiling Qt5 over and over again).

> That sounds like you want conda-forge to fail

Of course I don't (you're aware of all the time I put in conda-forge, I think :-). I just want you (we, I should say, as I'm a conda-forge member too) to put the extra effort needed to do this the right way.

One thing I forgot to mention is that Qt4 is essentially broken in macOS 10.10 and higher. It gives odd segfaults and hiccups all the time, and besides it doesn't work in high DPI screens (which almost all Macs have these days). So pinning to it is not a real solution either. It just avoids breakages between conda-forge and defaults, and nothing more.

**Comment by ocefpaf** [comment]
> Of course I know that, but we (at Continuum) also faced similar problems (Ray, Mike and me spent countless hours debugging and re-compiling Qt5 over and over again).

Comparing `conda-forge` resources with continuum **is** comparing apples and oranges. That makes no sense.

> Of course I don't (you're aware of all the time I put in conda-forge, I think :-). I just want you (we, I should say, as I'm a conda-forge member too) to put the extra effort needed to do this the right way.

So you know should that is not possible at the moment. There is no need to ship broken packages when a solution exists.

> So pinning to it is not a real solution either. It just avoids breakages between conda-forge and defaults, and nothing more.

That sounds like a solution for people that relies on `conda-forge` packages.

Either way I don't own a Mac to create the Qt builds and all the volunteers that said they could do it did not, you included, so why block a solution that ensures stability to `conda-forge` users? Why turn a blind eye and force people towards what they cannot do?

**Comment by ccordoba12** [comment]
> Comparing conda-forge resources with continuum is comparing apples and oranges

We are only four people building packages in Continuum, almost the same as you (well, Jonathan is with us now). And I'm not that active in the Anaconda team right now.

> So you know should that is not possible at the moment.

It is. @gillins is working on it right now.

> you included

Sure, I'd do it if I wouldn't be maintaining a major project and its several external plugins right now :-) But nevertheless (now that Easter is coming) I can put some time to make it happen.

> Why turn a blind eye and force people towards what they cannot do?

Because it is not the right way to do it. Why pin Qt today and un-pin it in a couple of weeks? It's just a waste of resources and time too.

**Comment by ocefpaf** [comment]
> Because it is not the right way to do it. Why pin Qt today and un-pin it in a couple of weeks? It's just a waste of resources and time too.

Weeks? It has been way more than so far.

PS: again the comparisons with `continuum` and `conda-forge` are meaningless as I said before. There is nothing to do with people.

**Comment by ccordoba12** [comment]
Ok, to arrive to a compromise, I think we should pin to `pyqt 4` but *only* for macOS and until Qt5 packages are available.

Too bad for their users (because of what I said above about Qt4 on 10.10+). But other platforms shouldn't be affected by this because they already have Qt5 packages. 

(And @ReimarBauer beat me to do it because that's exactly what he just did :-)

**Comment by ReimarBauer** [comment]
@ccordoba12 @ocefpaf I don't own an OSX System. I think selector is a good choice to have an ancient version for OSX. I am currently not sure if one of the older OSX packages of mss have been working before. However this one will do it. 

It is still complicated for me to figure  which package I have to mention in meta.yaml for build and which not. The selector is currently also a test. I am not sure if I could ommit  pyqt and qt for the other OSs.

**Pull request merged**
