### PR TITLE
1.3.2

### PR DESCRIPTION
**Pull request by ReimarBauer**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@ReimarBauer It would be nice to wait for the CIs to complete before merging.

**Comment by ReimarBauer** [comment]
Am 17.02.2017 8:55 nachm. schrieb "Filipe" <notifications@github.com>:

@ReimarBauer <https://github.com/ReimarBauer> It would be nice to wait for
the CIs to complete before merging.


Hmm. Does this also mean if I have pushed some incomplete version to my
fork that I anyway have to increase the build number?
Somehow I thought I would start the whole build process by merging.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/mss-feedstock/pull/7#issuecomment-280750488>,
or mute the thread

**Comment by ocefpaf** [comment]
> Hmm. Does this also mean if I have pushed some incomplete version to my
fork that

Only if the builds on `master` fails. Linux and Windows already passed. `OS X` you can follow here: https://travis-ci.org/conda-forge/mss-feedstock

> I anyway have to increase the build number?

When updating to a new version you don't need to increase the build number.

> Somehow I thought I would start the whole build process by merging.

You start the build+publish process. The build process start with the PR and, if they pass, we merge to publish.

**Comment by ReimarBauer** [comment]
Am 17.02.2017 10:38 nachm. schrieb "Filipe" <notifications@github.com>:

Hmm. Does this also mean if I have pushed some incomplete version to my
fork that

Only if the builds on master fails. Linux and Windows already passed. OS X
you can follow here: https://travis-ci.org/conda-forge/mss-feedstock

I anyway have to increase the build number?

When updating to a new version you don't need to increase the build number.

Somehow I thought I would start the whole build process by merging.

You start the build+publish process. The build process start with the PR
and, if they pass, we merge to publish.


Then I was just impatient. I have not seen that the Mac OSX build was going
on and restarted it. There was only one merge.

Thx

Reimar


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/mss-feedstock/pull/7#issuecomment-280773577>,
or mute the thread

**Comment by ocefpaf** [comment]
> Then I was just impatient. I have not seen that the Mac OSX build was going
on and restarted it. There was only one merge.

When Travis-CI is building OS X it can get  awfully slow. Re-starting only puts you in the back of the queue making it take longer.

**Comment by ReimarBauer** [comment]
On Fri, Feb 17, 2017 at 11:45 PM, Filipe <notifications@github.com> wrote:

> Then I was just impatient. I have not seen that the Mac OSX build was going
> on and restarted it. There was only one merge.
>
> When Travis-CI is building OS X it can get awfully slow. Re-starting only
> puts you in the back of the queue making it take longer.
>
Good Morning :)

Getting back on this. Only https://travis-ci.org/conda-forge/mss-feedstock
rebuilds the old version 1.3.1.

From the logfile
git checkout -qf 6609b75025bfbed06cb3f6d3c9ca3a3b2fb2816a

commit 6609b75025bfbed06cb3f6d3c9ca3a3b2fb2816a
Merge: 8c64c3e a511723
Author: Filipe <ocefpaf@gmail.com>
Date:   Fri Feb 3 10:37:35 2017 -0300

    Merge pull request #6 from ocefpaf/update_icu_pin

    Update icu pin

This works, but now I need help to try with 1.3.2

best regards

Reimar

**Comment by ocefpaf** [comment]
You are looking at the wrong Travis-CI build log. You must wait for this one: https://travis-ci.org/conda-forge/mss-feedstock/builds/202745254

**Pull request merged**
